### ISSUE TITLE
Different batch sizes give different test accuracies

### ISSUE THREAD

**Issue by fanlu** [gogyzzz/localatt_emorecog#2]
Hi @gogyzzz, I have a strange problem.
When I used different batch_size to test evaluation dataset. I got different test_accuracies.
```
batch_size:1
[test] score: 0.536, loss: 0.651, p_score: 0.536, f1_score: 0.536
```
```
batch_size:64
[test] score: 0.921, loss: 0.395, p_score: 0.923, f1_score: 0.921
```
Do you have any ideas about this problem? thanks.

**Comment by gogyzzz** [comment]
hello, fanlu. 
The batch size is important factor for model training.
Thanks.
